// General User Authentication Actions
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

// Fetch User Authorization Actions
export const FETCH_USER_AUTHORIZATION_START = 'FETCH_USER_AUTHORIZATION_START';
export const FETCH_USER_AUTHORIZATION_SUCCESS = 'FETCH_USER_AUTHORIZATION_SUCCESS';
export const FETCH_USER_AUTHORIZATION_FAILED = 'FETCH_USER_AUTHORIZATION_FAILED';
export const SELECT_TENANT = 'SELECT_TENANT';

// Service Actions
export const FETCH_SERVICELIST_START = 'FETCH_SERVICELIST_START';
export const FETCH_SERVICELIST_SUCCESS = 'FETCH_SERVICELIST_SUCCESS';
export const FETCH_SERVICELIST_FAILED = 'SERVICELIST_FAILED';
export const SELECT_SERVICE= 'SELECT_SERVICE';


// Service Actions
export const LOAD_SERVICE_PAGE_DATA_START = 'LOAD_SERVICE_PAGE_DATA_START';
export const LOAD_SERVICE_PAGE_DATA_SUCCESS = 'LOAD_SERVICE_PAGE_DATA_SUCCESS';
export const LOAD_SERVICE_PAGE_DATA_FAILED= 'LOAD_SERVICE_PAGE_DATA_FAILED';
export const ADD_NEW_SERVICE_START = 'ADD_NEW_SERVICE_START';
export const ADD_NEW_SERVICE_SUCCESS= 'ADD_NEW_SERVICE_SUCCESS';
export const ADD_NEW_SERVICE_FAILED= 'ADD_NEW_SERVICE_FAILED';
export const UPDATE_SERVICE_START = 'UPDATE_SERVICE_START';
export const UPDATE_SERVICE_SUCCESS= 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAILED= 'UPDATE_SERVICE_FAILED';
