apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
  namespace: prisma
  labels:
    stage: production
    name: database
    app: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: database
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:11.1'
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: postgres-5432
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config    
          volumeMounts:
            - name: database-disk
              readOnly: false
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: database-disk
          persistentVolumeClaim:
            claimName: database-disk
