apiVersion: v1
kind: Service
metadata:
  name: prisma
  namespace: prismatest
spec:
  ports:
  - name: prisma
    port: 4466
    targetPort: 4466
    protocol: TCP
  selector:
    stage: production
    name: prisma
    app: prisma

